// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJPjw84-KQmzxUhoOGCNSmH6L7oDDC44s',
    appId: '1:316749261916:web:89390314a15e533bc60a99',
    messagingSenderId: '316749261916',
    projectId: 'quiz--app-e7402',
    authDomain: 'quiz--app-e7402.firebaseapp.com',
    storageBucket: 'quiz--app-e7402.firebasestorage.app',
    measurementId: 'G-Z80WJ38875',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzndg5guV8W7ZX9CabJe677-E-tKf8M6g',
    appId: '1:316749261916:android:80416877eed23608c60a99',
    messagingSenderId: '316749261916',
    projectId: 'quiz--app-e7402',
    storageBucket: 'quiz--app-e7402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCT053ja3NI6khvA-m21ofeoh4trlTrifY',
    appId: '1:316749261916:ios:80fdc8ceaca5ddf9c60a99',
    messagingSenderId: '316749261916',
    projectId: 'quiz--app-e7402',
    storageBucket: 'quiz--app-e7402.firebasestorage.app',
    iosClientId: '316749261916-a1g7gnvgt2vb7h1a2lb4bj985k43od01.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuizPro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCT053ja3NI6khvA-m21ofeoh4trlTrifY',
    appId: '1:316749261916:ios:80fdc8ceaca5ddf9c60a99',
    messagingSenderId: '316749261916',
    projectId: 'quiz--app-e7402',
    storageBucket: 'quiz--app-e7402.firebasestorage.app',
    iosClientId: '316749261916-a1g7gnvgt2vb7h1a2lb4bj985k43od01.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalQuizPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJPjw84-KQmzxUhoOGCNSmH6L7oDDC44s',
    appId: '1:316749261916:web:3da8abb66a2da3edc60a99',
    messagingSenderId: '316749261916',
    projectId: 'quiz--app-e7402',
    authDomain: 'quiz--app-e7402.firebaseapp.com',
    storageBucket: 'quiz--app-e7402.firebasestorage.app',
    measurementId: 'G-XH3CN1X5VD',
  );
}
